[package]
name = "phone_location"
version = "0.1.0"
authors = ["incoknito"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.5"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.69"